title: MISCELLANEOUS NOTES
name: euikook
email: euikook@gmail.com
description: Miscellaneous notes by E.K. KIM

# baseurl: "/blog"
# url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/highlighted-code.png # These are the images used for the parallax background
parallax_image_two: assets/images/highlighted-code.png


projects_heading: Projects
projects_type: cards

projects:
  - name: "python-backupman"
    image: "databackup.jpg"
    description: Incremental Backup using RSYNC, SSH, CRON
    url: https://github.com/grepos/python-backupman
    icon: location_on
    button: github
  - name: "backupman"
    image: "databackup.jpg"
    description: Incremental Backup using RSYNC, SSH, CRON
    url:  https://github.com/grepos/backupman
    icon: photo_camera
    button: github


icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/euikook
medium: https://blog.gitkat.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: https://grepos.com #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # GTM-MPRJ93G # This looks something like GTM-XXXXXXX
analytics_id: UA-113420644-1 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown

highlighter: rouge

# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

include: ['_pages']

# exclude: ['README.md']
