baseURL = "http://harues.com/"
languageCode = "en-us"
title = "Miscellaneous Notes"
theme = "anatole"
staticDir = ["static"]

[params]
title = "I'm euikook"
author = "euikook"
description = "Call me Jane"
profilePicture = "images/logo.png"
