# Set base URL for site - should end with a trailing slash
baseUrl = "https://notes.oneuon.com/"

theme = "slick"

# Site title (not shown if commented out or set to false)
# (If you disable this, add some link on the index page inside menu.main,
#  otherwise your visitors will get confused and lost...)
title = "Notes"

languageCode = "en"
defaultContentLanguage = "en"

googleAnalytics = "G-XR6RLEW3M1"

# Will appear below the footer links with a © sign and the current year
copyright = "All rights reserved."

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet

canonifyURLs = true

# Configure pagination
paginate = 10
paginatePath = "page"


[params]
    # Site subtitle (not shown if commented out or set to false)
    subtitle = "Miscellaneous Notes"

    # Site description
    description = "Notes by euikook."

    # Favicon file (relative to baseURL - place below static or assets folder)
    favicon = "favicon.png"
    # Custom css file (relative to baseURL - place below static or assets folder)
    css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateFmt = "Mon, 02 Jan 2006"

    # Customize the text of the 404 page here
    errorPageText = "There's nothing to see here, please move along!"

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # If false the RSS link in footer is not shown
    showRssLink = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = true

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = true

    # If false the title, dates and taxonomy are not shown on single view
    showMeta = true

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false

    katex = true


# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"


[author]
    name = "euikook"
    email = "euikook@gmail.com"
    bio = "/about"


[services.rss]
    # limit the length of the rss feed (default: unlimited)
    limit = 0


[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 1

    #[[menu.main]]
    #    identifier = "categories"
    #    name = "Categories"
    #    title = "All categories"
    #    url = "/categories/"
    #    weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        title = "All tags"
        url = "/tags/"
        weight = 2

    [[menu.main]]
        identifier = "series"
        name = "Series"
        title = "All series"
        url = "/series/"
        weight = 2


    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "categories"
        name = "Categories"
        weight = 1
    [[menu.meta]]
        identifier = "series"
        name = "Series"
        weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Github"
        url = "https://github.com/euikook"
        weight = 1

    #[[menu.footer]]
    #    name = "Slick"
    #    title = "Theme page on gohugo.io"
    #    url = "https://themes.gohugo.io/slick"
    #    weight = 2

    #[[menu.footer]]
    #    name = "Toor"
    #    title = "Some website, using this theme"
    #    url = "https://www.toor.su"
    #    weight = 3


# Enable generation of robots.txt
enableRobotsTXT = true

# Configure sitemap
[sitemap]
  # Values are 'always', 'hourly', 'daily',' weekly', 'monthly', 'yearly',
  # and 'never'. Set to empty string to omit inclusion
  changefreq = "daily"
  # Adjust filename of sitemap. (default: sitemap.xml)
  filename = "sitemap.xml"
  # Values range from 0.0 to 1.0. Set to -1 to omit inclusion
  priority =  -1


[params.adsense]
  id = "ca-pub-1494649960951277"


[params.utterances]
    repo = "euikook/wiki.notes"
    term = "pathname"
    theme = "github-light"
    crossorigin = "anonymous"

