#!/usr/bin/env node

var fs = require('fs');
var yamlfront = require('yaml-front-matter');
var glob = require('glob');
var slugify = require('slugify')


var postdir = './_posts';
var tagdir = './tags';

files = glob.sync(postdir + '/*.md');

/* Read Tags */
let tags = [];
for (let file of files) {

    let contents = fs.readFileSync(file, 'utf8');
    parsed = yamlfront.loadFront(contents);

    if (parsed.tags) {

        for (let tag of parsed.tags) {

            if (tags.indexOf(tag) === -1) {
                tags.push(tag)
            }
        }
    }
}

/* Remove all files in tags */
files = fs.readdirSync(tagdir);
for (let file of files) {
    if (file === 'index.html') continue;
    fs.unlinkSync(tagdir + '/' + file);
}
;

/* Create Tag page */
for (let tag of tags) {
    const opts = {
        replacement: '-',    // replace spaces with replacement
        remove: null,        // regex to remove characters
        lower: true          // result in lower case
    }
    let location = 'tags/' + slugify(tag, opts) + '.md';
    let content = [
        '---',
        'layout: tagpage',
        'title: "Tag: ' + tag + '"',
        'tag: ' + tag,
        'robots: noindex',
        '---',
        ''
    ].join('\n');

    fs.writeFileSync(location, content, (err) => {
        if (err) {
            return console.log(err);
        }
    })
}
