#!/usr/bin/env bash
msg=${1:-"Update posts"}

${dryrun} cd content/posts
${dryrun} git add .
${dryrun} git commit -S -m "${msg}"
${dryrun} git push
${dryrun} cd -
${dryrun} git add .
${dryrun} git commit -S -m "${msg}"
${dryrun} git push
