#!/usr/bin/env bash
msg=${1:-"Update posts"}

${dryrun} cd themes/hugo-icarus
${dryrun} git add .
${dryrun} git commit -m "${msg}"
${dryrun} git push
${dryrun} cd -
${dryrun} git add .
${dryrun} git commit -m "${msg}"
${dryrun} git push
